---
dependencies:
  - kewlfft.aur

galaxy_info:
  role_name: desktop
  author: jnsgruk
  description: Installs Desktop tools
  license: MIT
  min_ansible_version: 2.4
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Archlinux
      versions:
        - all
