---
- name: Create directories if non-existent
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - ~/.config/htop
    - ~/.ssh
    - ~/.tmux/plugins

- name: Create config symlinks
  file:
    src: "{{ playbook_dir }}/dots/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  loop:
    - { src: "shell/.gitconfig", dest: ~/.gitconfig }
    - { src: "shell/.gitignore", dest: ~/.gitignore }
    - { src: "shell/tmux.conf", dest: ~/.tmux.conf }
    - { src: "shell/htoprc", dest: ~/.config/htop/htoprc }
    - { src: "shell/starship.toml", dest: ~/.config/starship.toml }
    - { src: "shell/starship-plain.toml", dest: ~/.config/starship-plain.toml }

- name: Copy .gitconfig template
  copy:
    src: "{{ playbook_dir }}/dots/shell/.gitconfig"
    dest: "~/.gitconfig"
    remote_src: true

- name: Install zshrc and config
  file:
    src: "{{ playbook_dir }}/dots/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  loop:
    - { src: "shell/.zsh_config", dest: ~/.zsh_config }
    - { src: "shell/.zshrc", dest: ~/.zshrc }

- name: Install zsh plugins & themes
  git:
    repo: "https://github.com/{{ item.repo }}"
    dest: "~/.zsh_config/{{ item.dest }}"
  loop:
    - { repo: "zsh-users/zsh-autosuggestions", dest: "zsh-autosuggestions" }
    - { repo: "zsh-users/zsh-syntax-highlighting", dest: "zsh-syntax-highlighting" }


- name: Install tpm and plugins
  git:
    repo: "https://github.com/{{ item.repo }}"
    dest: "~/.tmux/plugins/{{ item.dest }}"
  loop:
    - { repo: "tmux-plugins/tpm", dest: "tpm" }


- name: Change default shell
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

- name: Install zshrc (root)
  become: yes
  copy:
    src: "{{ playbook_dir }}/dots/shell/root.zshrc"
    dest: "/root/.zshrc"
    owner: root
    group: root
    mode: "0600"
    force: yes

- name: Create directories if non-existent (root)
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /root/.config

- name: Install starship config (root)
  become: yes
  copy:
    src: "{{ playbook_dir }}/dots/shell/starship-plain.toml"
    dest: "/root/.config/starship-plain.toml"
    owner: root
    group: root
    mode: "0600"
    force: yes

- name: Change default shell (root)
  become: yes
  user:
    name: root
    shell: /bin/zsh
