---
- name: Install Bat (Debian/Ubuntu/RHEL/Fedora)
  become: true
  block:
    - name: Download bat
      get_url:
        url: "https://github.com/sharkdp/bat/releases/download/v{{ bat_version }}/bat-v{{ bat_version }}-x86_64-unknown-linux-gnu.tar.gz"
        checksum: "{{ bat_checksum }}"
        dest: "{{ tmp_dir }}/bat.tar.gz"
        mode: "0600"

    - name: Extract bat
      unarchive:
        src: "{{ tmp_dir }}/bat.tar.gz"
        dest: "{{ tmp_dir }}"
        remote_src: yes

    - name: Install bat
      become: yes
      copy:
        src: "{{ tmp_dir }}/bat-v{{ bat_version }}-x86_64-unknown-linux-gnu/bat"
        dest: "{{ install_dir }}/bat"
        mode: "0755"
        owner: "root"
        group: "root"
        remote_src: yes
  when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'

- name: Install Bat (Arch)
  become: yes
  pacman:
    name: bat
    state: present
    update_cache: true
  when: ansible_os_family == 'Archlinux'
