---
- name: Install zsh
  become: yes
  package:
    name: zsh
    state: present

- name: Download oh-my-zsh setup
  become: yes
  get_url:
    url: "https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh"
    dest: /tmp/oh-my-zsh.sh
    mode: "0755"

- name: Install oh-my-zsh (current user)
  command: /tmp/oh-my-zsh.sh --unattended --keep-zshrc
  args:
    creates: ~/.oh-my-zsh

- name: Install zshrc
  file:
    src: "{{ playbook_dir }}/dots/shell/.zshrc"
    dest: "~/.zshrc"
    state: link
    force: yes

- name: Install zshrc and config
  file:
    src: "{{ playbook_dir }}/dots/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  loop:
    - { src: "shell/.zsh_config", dest: ~/.zsh_config }
    - { src: "shell/.zshrc", dest: ~/.zshrc }

- name: Change default shell
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

- name: Install oh-my-zsh (root)
  become: yes
  become_user: root
  command: "/tmp/oh-my-zsh.sh --unattended --keep-zshrc"
  args:
    creates: /root/.oh-my-zsh

- name: Install zshrc (root)
  become: yes
  copy:
    src: "{{ playbook_dir }}/dots/shell/root.zshrc"
    dest: "/root/.zshrc"
    owner: root
    group: root
    mode: "0600"
    force: yes

- name: Change default shell (root)
  become: yes
  user:
    name: root
    shell: /bin/zsh
