---
- name: Install vim
  become: yes
  package:
    name: vim
    state: present

- name: Create .vim directory
  file:
    path: "~/.vim/bundle"
    state: directory
    mode: "0755"

- name: Create Symlinks
  file:
    src: "{{ playbook_dir }}/dots/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  loop:
    - { src: "shell/.vimrc", dest: ~/.vimrc }
    - { src: "shell/setup.vim", dest: ~/.vim/setup.vim }

- name: Clone Vundle plugin manager
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: ~/.vim/bundle/Vundle.vim

- name: Install Vim plugins
  command: vim -s ~/.vim/setup.vim
  ignore_errors: yes
