---
- name: Install dependencies from archive
  become: yes
  apt:
    update_cache: yes
    state: present
    name: "{{ item }}"
  loop:
    - ca-certificates
    - curl
    - apt-transport-https
    - lsb-release
    - gnupg

- name: Trust Microsoft apt signing key
  become: yes
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/microsoft.gpg
    state: present

- name: Add apt source list
  become: yes
  template:
    src: templates/azure-cli.list.j2
    dest: /etc/apt/sources.list.d/azure-cli.list

- name: Install Azure CLI
  become: yes
  apt:
    name: azure-cli
    state: present
    update_cache: yes
