---
- hosts: localhost
  tasks:
    - name: Setup shell
      include_role:
        name: shell
      when: install_shell

    - name: Setup fonts
      include_role:
        name: fonts
      when: install_fonts
