---
- name: Install 1Password (Debian)
  block:
    - name: Install dependencies from archive
      become: yes
      apt:
        update_cache: yes
        state: present
        name: "{{ item }}"
      loop:
        - ca-certificates
        - wget
        - apt-transport-https
        - software-properties-common
        - gpg

    - name: Trust 1Password apt signing key
      become: yes
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 3FEF9748469ADBE15DA7CA80AC2D62742012EA22

    - name: Add apt source list
      become: yes
      copy:
        src: files/1password.list
        dest: /etc/apt/sources.list.d/1password.list

    - name: Install 1Password
      become: yes
      apt:
        name: 1password
        state: present
        update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install 1Password (Arch)
  block:
    - name: Create aur_builder user
      become: true
      user:
        name: aur_builder
        group: wheel

    - name: Configure aur_builder user
      become: true
      lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
        create: yes
        validate: "visudo -cf %s"

    - name: Install 1Password (Arch)
      become: yes
      become_user: aur_builder
      aur:
        use: yay
        name: 1password

    - name: Delete aur_builder user
      become: true
      user:
        name: aur_builder
        state: absent
        remove: yes

    - name: Reconfigure sudoers (remove aur_builder)
      become: true
      file:
        path: /etc/sudoers.d/11-install-aur_builder
        state: absent

  when: ansible_os_family == "Archlinux"
