---
- name: Install Discord (Debian)
  block:
    - name: Install Discord
      become: yes
      apt:
        deb: "https://discord.com/api/download?platform=linux&format=deb"
  when: ansible_os_family == "Debian"

- name: Install Signal (Arch)
  become: yes
  pacman:
    name: discord
    state: present
    update_cache: true
  when: ansible_os_family == "Archlinux"
