---
- name: Install Discord (Debian)
  block:
    - name: Install Discord
      become: yes
      snap:
        name: discord
  when: ansible_os_family == "Debian"

- name: Install Signal (Arch)
  become: yes
  pacman:
    name: discord
    state: present
    update_cache: true
  when: ansible_os_family == "Archlinux"
