---
- name: Install desktop apps
  block:
    - include_tasks: xdg-user-dirs.yml
    - include_tasks: tilix.yml
    - include_tasks: signal.yml
    - include_tasks: vscode.yml
    - include_tasks: 1password.yml
    - include_tasks: discord.yml
    - include_tasks: spotify.yml
    - include_tasks: nextcloud.yml
    # - include_tasks: terminator.yml
  when: desktop_force or (display | length > 0)
