---
- name: Install nextcloud
  become: true
  package:
    name: nextcloud-desktop
    state: present
  when:
    - ansible_distribution == 'Ubuntu'

- name: Install nextcloud
  become: true
  package:
    name: nextcloud-client
    state: present
  when: ansible_os_family == "Archlinux"
