---
- name: Install Signal (Ubuntu)
  block:
    - name: Install Signal
      become: yes
      snap:
        name: signal-desktop
  when: ansible_os_family == "Debian"

- name: Install Signal (Arch)
  become: yes
  pacman:
    name: signal-desktop
    state: present
    update_cache: true
  when: ansible_os_family == "Archlinux"
