---
- name: Install Spotify (Debian)
  block:
    - name: Install dependencies from archive
      become: yes
      apt:
        update_cache: yes
        state: present
        name: "{{ item }}"
      loop:
        - ca-certificates
        - wget
        - apt-transport-https
        - software-properties-common
        - gpg

    - name: Trust Spotify apt signing key
      become: yes
      apt_key:
        url: https://download.spotify.com/debian/pubkey_0D811D58.gpg
        keyring: /etc/apt/trusted.gpg.d/spotify.gpg
        state: present

    - name: Add apt source list
      become: yes
      copy:
        src: files/spotify.list
        dest: /etc/apt/sources.list.d/spotify.list

    - name: Install Spotify
      become: yes
      apt:
        name: spotify-client
        state: present
        update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install  Spotify (Arch)
  block:
    - name: Create aur_builder user
      become: true
      user:
        name: aur_builder
        group: wheel

    - name: Configure aur_builder user
      become: true
      lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
        create: yes
        validate: "visudo -cf %s"

    - name: Install Spotify (Arch)
      become: yes
      become_user: aur_builder
      aur:
        use: yay
        name: spotify

    - name: Delete aur_builder user
      become: true
      user:
        name: aur_builder
        state: absent
        remove: yes

    - name: Reconfigure sudoers (remove aur_builder)
      become: true
      file:
        path: /etc/sudoers.d/11-install-aur_builder
        state: absent

  when: ansible_os_family == "Archlinux"
