---
- name: Install terminator
  become: true
  package:
    name: terminator
    state: present

- name: Create terminator config directory
  file:
    path: "~/.config/terminator"
    state: directory
    mode: "0755"

- name: Symlink terminator config
  file:
    src: "{{ playbook_dir }}/dots/desktop/terminator_config"
    dest: "~/.config/terminator/config"
    state: link
    force: yes
