---
dependencies: []

galaxy_info:
  role_name: goenv
  author: jnsgruk
  description: Install goenv
  company: ""
  license: MIT
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Archlinux
      versions:
        - all
