---
- name: Clone goenv
  git:
    repo: "https://github.com/syndbg/goenv.git"
    dest: "~/.goenv"

- name: "Install Go {{ goenv_go_version}}"
  shell: ~/.goenv/bin/goenv install -s "{{ goenv_go_version }}"

- name: "Set global go version to {{ goenv_go_version }}"
  shell: ~/.goenv/bin/goenv global "{{ goenv_go_version }}"
  when: goenv_set_global_go
