---
- name: Install Python build dependencies (Debian/Ubuntu)
  become: true
  apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  loop:
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - wget
    - curl
    - llvm
    - libncurses5-dev
    - libncursesw5-dev
    - xz-utils
    - tk-dev
    - libffi-dev
    - liblzma-dev
    - python3-openssl
    - git

- name: Install Python 2 dependencies
  become: true
  apt:
    name: python-openssl
    update_cache: true
    state: present
  when: ansible_distribution_release == "focal" or ansible_distribution_release == "bionic"
