---
- name: Install Python build dependencies (Arch)
  become: true
  pacman:
    name: "{{ item }}"
    update_cache: true
    state: present
  loop:
    - base-devel
    - openssl
    - zlib
    - bzip2
    - readline
    - sqlite
    - curl
    - llvm
    - ncurses
    - xz
    - tk
    - libffi
    - python-pyopenssl
    - git
