- name: Install Docker Compose
  become: yes
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    checksum: "{{ docker_compose_checksum }}"
    dest: "{{ install_dir }}/docker-compose"
    mode: 0755
  when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

- name: Install Docker Compose (Arch)
  become: yes
  pacman:
    name: docker-compose
    state: present
    update_cache: yes
  when: ansible_os_family == "Archlinux"
