---
- name: Install dependencies from archive
  become: yes
  apt:
    update_cache: yes
    state: present
    name: "{{ item }}"
  loop:
    - ca-certificates
    - curl
    - apt-transport-https
    - software-properties-common
    - gnupg-agent

- name: Trust Docker apt signing key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Get Ubuntu Release
  command: lsb_release -cs
  register: lsb_output

- name: Set Release Repo (xenial/bionic/focal)
  set_fact:
    ubuntu_release: "{{ lsb_output.stdout }}"

- name: Set Release Repo (groovy)
  set_fact:
    ubuntu_release: focal
  when: lsb_output.stdout == "groovy"

- name: Add apt source list
  become: yes
  template:
    src: templates/docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list

- name: Install Docker
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
