---
- name: Import Docker repository key
  become: yes
  rpm_key:
    state: present
    key: https://download.docker.com/linux/centos/gpg

- name: Add Docker repo
  become: yes
  template:
    src: templates/docker.repo.j2
    dest: /etc/yum.repos.d/docker.repo

- name: Install Docker
  become: yes
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
