---
- name: Delete aur_builder user
  become: true
  user:
    name: aur_builder
    state: absent
    remove: yes

- name: Reconfigure sudoers (remove aur_builder)
  become: true
  file:
    path: /etc/sudoers.d/11-install-aur_builder
    state: absent
