---
- name: Install istioctl
  block:
    - name: Download istioctl tarball
      get_url:
        url: "https://github.com/istio/istio/releases/download/{{ istioctl_version }}/istioctl-{{ istioctl_version }}-{{ os }}-{{ architecture }}.tar.gz"
        checksum: "{{ istioctl_checksum }}"
        dest: "{{ tmp_dir }}/istioctl.tar.gz"

    - name: Extract istioctl tarball
      unarchive:
        src: "{{ tmp_dir }}/istioctl.tar.gz"
        dest: "{{ tmp_dir }}"
        remote_src: yes

    - name: Install istioctl
      become: yes
      copy:
        src: "{{ tmp_dir }}/{{ item }}"
        dest: "{{ install_dir }}/{{ item }}"
        mode: "0755"
        owner: "{{ owner }}"
        group: "{{ group }}"
        remote_src: yes
      with_items:
        - istioctl
  when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

- name: Install istioctl (Arch)
  become: yes
  become_user: aur_builder
  aur:
    use: yay
    name: istio-bin
  when: ansible_os_family == "Archlinux"
