---
- name: Install kubectl (Debian/Ubuntu)
  block:
    - name: Install dependencies from archive
      become: yes
      apt:
        update_cache: yes
        state: present
        name: "{{ item }}"
      loop:
        - curl
        - apt-transport-https
        - gnupg2

    - name: Trust Google apt signing key
      become: yes
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        keyring: /etc/apt/trusted.gpg.d/kubectl.gpg
        state: present

    - name: Add apt source list
      become: yes
      copy:
        src: files/kubernetes.list
        dest: /etc/apt/sources.list.d/kubernetes.list
        mode: 644

    - name: Install kubectl
      become: yes
      apt:
        name: kubectl
        state: present
        update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install kubectl (CentOS/RHEL/Fedora)
  block:
    - name: Add yum repo
      become: yes
      copy:
        src: files/kubernetes.repo
        dest: /etc/yum.repos.d/kubernetes.repo
        mode: 644

    - name: Install kubectl
      become: yes
      apt:
        name: kubectl
        state: present
        update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Install kubectl (Arch)
  become: yes
  pacman:
    name: kubectl
    state: present
    update_cache: true
  when: ansible_os_family == "Archlinux"
